# site settings
title: Aldoyh
subtitle: Not Just Another Portfolio
email: aldoyh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Aldoyh is a portfolio website for Hasan AlDoy, a web developer based in Bahrain. This website was made with Love ❤️ and Jekyll.
baseurl: "/welcome" # the subpath of your site, e.g. /blog

url: "https://aldoyh.github.io/forty-jekyll-theme/" # the base hostname & protocol for your site
author: Hasan AlDoy # all posts will have this author unless specified otherwise
street_address: 33 Bahrain Avenue
city: AlMuharraq
state: Bahrain
zip_code: 1111
country: Bahrain
phone: +973 3333 3333

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/aldoyh
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/aldoyh
  Twitter: https://twitter.com/aldoyh
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
